# Basic Site Settings
locale                  : "es-CL"
site_theme               : "default" 
title                    : "Isaac Peña-Villalobos, PhD"
title_separator          : "|"
name                     : &name "Isaac Peña-Villalobos"
description              : &description "Investigador en Ecología Evolutiva, Fisiología Integrativa y Salud Ambiental."
url                      : "https://ipenavillalobos-ui.github.io" # Reemplaza 'isaacpena' con tu usuario real de GitHub
baseurl                  : "" 
repository               : "ipenavillalobos-ui.github.io" # Reemplaza con tu repositorio

# Site Author
author:
  avatar           : "profile.png" # Sube una foto con este nombre a la carpeta /images/
  name             : "Isaac Peña-Villalobos"
  pronouns         : "he/him"  
  bio              : "Doctor en Ciencias c/m en Ecología y Biología Evolutiva. Investigador Responsable FONDECYT."
  location         : "Santiago, Chile"
  employer         : "Universidad de Chile"
  uri              : 
  email            : "isaac.pena@uchile.cl" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ" # Confirma que este sea tu ID
  orcid            : "https://orcid.org/0000-0002-5599-5290"
  researchgate     : "https://www.researchgate.net/profile/Isaac-Peña-Villalobos"
  pubmed           : "https://pubmed.ncbi.nlm.nih.gov/?term=Pena-Villalobos+I"
  
  # Repositories and software development
  github           : "isaacpena" # Tu usuario de GitHub

# Publication Category
publication_category:
  manuscripts:
    title: 'Artículos en Revistas Científicas'    
  conferences:
    title: 'Congresos y Conferencias'

# SEO Related
google_site_verification :
bing_site_verification   :

# Social Sharing
twitter:
  username               : 
facebook:
  username               : 
  
# Analytics
analytics:
  provider               : "false" # Cambia a "google" si luego quieres ver quién visita tu web

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - Gemfile
  - node_modules
  - package.json*
  - README
  - vendor

# Collections Settings
collections:
  teaching:
    output: true
    permalink: /docencia/:path/
  publications:
    output: true
    permalink: /publicaciones/:path/
  portfolio:
    output: true
    permalink: /proyectos/:path/
  talks:
    output: true
    permalink: /charlas/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
